### ISSUE TITLE
Add links to issues and PRs in CHANGELOG

### ISSUE THREAD

**Issue by yohanboniface** [pyrates/roll#18]
The changelog documentation states that a changelog should link to related issues… but we don't do it! :p

**Comment by davidbgk** [comment]
Alright, let's do that from now on or the issue is here to fix previous releases changelog?

**Comment by yohanboniface** [comment]
I meant mainly for not forgetting to raise the discussion :)

Ideally, I'd say adding links in the already existing changes would be better, but lt's see if one of us find the occasion to do so in the incoming days, otherwise let's close and just try to think about it in the future :)
