### ISSUE TITLE
ImportError: cannot import name 'HttpParserUpgrade' from 'httptools'

### ISSUE THREAD

**Issue by JulienPalard** [pyrates/roll#62]
On a manually-built release of httptools (`git clone https://github.com/1st1/httptools.git`, `git submodule update --init`, `make compile`, `pip install .`), I'm getting this `ImportError`.

**Comment by yohanboniface** [comment]
Weird.
I cannot reproduce. :(
Can you try `dir(httptools)` to have a rough idea of what's going on?

```
In [2]: import httptools

In [3]: dir(httptools)
Out[3]: 
['HttpParserCallbackError',
 'HttpParserError',
 'HttpParserInvalidMethodError',
 'HttpParserInvalidStatusError',
 'HttpParserInvalidURLError',
 'HttpParserUpgrade',
 'HttpRequestParser',
 'HttpResponseParser',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'parse_url',
 'parser']

In [4]: httptools.__file__
Out[4]: '/home/ybon/.virtualenvs/c3/lib/python3.7/site-packages/httptools/__init__.py'
```

**Comment by yohanboniface** [comment]
> (Note that grep -r did not find the string, is it an hint?).

Weirdissime.

BTW, the exception class comes from httptools itself, not from the http-parser submodule:

https://github.com/MagicStack/httptools/blob/master/httptools/parser/errors.py#L29

The thing is that you seem to have all the other Exception classes.

**Ah, hint:**

You are cloning from 1st1 repo, instead of from the MagicStack one? ;)

**Comment by JulienPalard** [comment]
Yup...
```
origin	https://github.com/1st1/httptools.git (fetch)
origin	https://github.com/1st1/httptools.git (push)
```

And I know remember how I got this wrong, the project on pypi did *not* had a link to the github project: https://pypi.org/project/httptools/ :(

**Comment by yohanboniface** [comment]
Made PR for this https://github.com/MagicStack/httptools/pull/30 :)

**Comment by JulienPalard** [comment]
Thanks Yohan :)) Sorry for the disturbance þ
